### ISSUE TITLE
Make use of disabling WiFi scan throttling inside developer options

### ISSUE THREAD

**Issue by AtmosphericIgnition** [mjaakko/NeoStumbler#141] opened 2024-07-16 18:43 UTC
By default, newer Android versions throttle the frequency of WiFi scanning by apps. The throttling can be disabled inside of Developer Options, at the expense of worse battery life. I have noticed that NeoStumbler often leaves out spots when I'm surveying while riding a bicycle, and taking advantage of this setting could (as far as I understand) help alleviate the issue.

Attached below is a screenshot from an app called [NetworkSurvey](https://github.com/christianrowlands/android-network-survey), which prompts the user to disable the setting for increased data accuracy. There is a page on [Android Developer](https://developer.android.com/develop/connectivity/wifi/wifi-scan) about the throttling behavior on different Android versions.

![signal-2024-07-16-203523](https://github.com/user-attachments/assets/14847633-f4d5-4e67-a6b7-9023416ec4e4)

**Comment by mjaakko** [comment] 2024-07-16 18:53
Duplicate of #140

**Closed by mjaakko** 2024-07-16 18:53 UTC
