### ISSUE TITLE
Failed to upload reports when trying to upload to Beacons

### ISSUE THREAD

**Issue by Elaborendum** [mjaakko/NeoStumbler#232] opened 2024-09-10 04:28 UTC
### Description

I thought I had enabled automatic upload, but turns out I hadn't and now I have about ~20000 non-uploaded reports in the app. Clicking "Send reports" results in the "Failed to upload reports" dialog, clicking it a second tim after this crashes the app.

### App variant

fdroid

### Version

1.3.1

### Device

Samsung A12

### Android version

Android 13

### New bug

- [X] I have checked that this bug has not been reported before

**Comment by joelkoen** [comment] 2024-09-10 04:29
BeaconDB is currently experiencing an outage, I'm posting updates in the Matrix room and will comment here once things are back online :)

**Comment by joelkoen** [comment] 2024-09-10 07:41
Back now.

But yeah, failing to upload to the server shouldn't crash the app.

**Comment by mjaakko** [comment] 2024-09-10 08:55
The crash should be fixed in master branch. I'll do some testing and close the issue if I can't reproduce this

**Comment by mjaakko** [comment] 2024-09-15 17:21
Closing this issue because the crash has been fixed

**Closed by mjaakko** 2024-09-15 17:21 UTC
Labels: bug
