### ISSUE TITLE
Can't enable automatic scanning on Pixel 6 running GrapheneOS

### ISSUE THREAD

**Issue by chetgurevitch** [mjaakko/NeoStumbler#129] opened 2024-07-11 05:09 UTC
As the title says I can't enable the automatic scanning option on my phone, It gets to https://github.com/mjaakko/NeoStumbler/blob/ce4d69b8657747e55c0acd43d9472371886d5017/app/src/full/kotlin/xyz/malkki/neostumbler/ui/composables/autoscan/AutoScanToggle.kt#L88 executes the nested calls all the way through https://github.com/mjaakko/NeoStumbler/blob/ce4d69b8657747e55c0acd43d9472371886d5017/app/src/full/kotlin/xyz/malkki/neostumbler/scanner/autoscan/ActivityTransitionReceiver.kt#L70 then just gets stuck trying to step over to the next line in AutoScanToggle.kt.
[Full thread dump.txt](https://github.com/user-attachments/files/16171662/Full.thread.dump.txt)

Visually this manifests as the toggle becoming greyed out and non-interactive until leaving and returning to the settings page. Using the Pixel 3a emulator in Android Studio there is no such problem and it activates fine.

**Comment by mjaakko** [comment] 2024-07-11 05:51
Automatic scanning uses Activity Recognition API from Google Play Services to detect when the device is moving. Does GrapheneOS have some type of implementation for that?

**Comment by chetgurevitch** [comment] 2024-07-11 06:14
GrapheneOS lets you install a sandboxed version of the regular play services, so I would assume so, although I can't find much reference to this particular permission and API. I may try making a testing app when I've got some time.

**Comment by mjaakko** [comment] 2024-07-11 08:42
I'm guessing what happens here is that GrapheneOS provides an stub implementation for some Google Play Services API which then never actually returns anything and that causes NeoStumbler to get stuck. I'll see if it would be possible to add a timeout so that the toggle doesn't get stuck if automatic scanning can't be enabled

**Comment by mjaakko** [comment] 2024-07-12 18:23
I've added a timeout for the toggle so that it doesn't get stuck if automatic scanning can't be enabled

**Comment by EchedelleLR** [comment] 2024-07-21 12:46
Could not you use accelerometer with the same algorithm used by pedometers?

**Comment by mjaakko** [comment] 2024-07-21 18:16
> Could not you use accelerometer with the same algorithm used by pedometers?

I'm not sure if Android provides a battery-friendly API to do this. But this would be one way to do automatic scanning without relying on Google Play Services

**Comment by EchedelleLR** [comment] 2024-07-21 18:33
Using a Pedometer app I found that they rely on it and also the possibility to use a hardware step counter which seems that some Android phones integrate which even uses less battery.

**Comment by mjaakko** [comment] 2024-07-23 18:02
Closing this issue because the root problem seems to be in a third-party implementation of Google Play Services and the UI getting stuck has been fixed

**Closed by mjaakko** 2024-07-23 18:02 UTC

**Comment by e-t-l** [comment] 2025-02-06 06:00
@mjaakko not sure about the "stuck ui" aspect, but i can report on Pixel 8 Pro with GrapheneOS, I'm getting the message "cannot enable automatic scanning" despite having granted all permissions.

I can also clarify that Graphene does NOT provide API stubs the way MicroG does; Graphene uses the full original Play Services apk; it just has a sandboxing layer to prevent it from doing the kind of automatic snooping it normally does on Android, such as full screen OCR.

Could Neostumbler perhaps have an option to start scanning when the device disconnects from selected SSIDs? This would essentially be like "when I leave home, start scanning."

**Comment by chetgurevitch** [comment] 2025-02-06 06:06
@e-t-l not all play services functionality is supported by the compatibility layer to run unprivileged, some is in fact stubbed, the message you're seeing is the result of the call timing out without response

**Comment by mjaakko** [comment] 2025-02-07 06:06
@e-t-l The error message is shown when the API timeouts. This is likely caused by the Google Play sandboxing layer

As for the feature you requested: No, it's not possible to do that, because Android does not have a battery-friendly API for apps to get a callback when disconnected from a Wi-Fi network. Geofencing APIs could be used to achieve similar results, but I think this use case could be fulfilled by improving the motion detection feature (e.g. #441, #254). This way you could keep NeoStumbler running in the background with very minimal battery impact and scanning would start automatically when moving
